### ISSUE TITLE
3.6 カルーセルの例  / リンク切れ

### ISSUE THREAD

**Issue by bakera** [waic/wai-aria-practices-11#5]
(問合せフォームより)
https://waic.jp/docs/2019/NOTE-wai-aria-practices-1.1-20190207/#carousel
参考にさせていただいております。
3.6 カルーセル（スライド・ショー、もしくは、イメージ・ローテーター）の例にある「自動回転するイメージ・カルーセルの例」のリンクがきれていました。
以下のリンクになるのかなと思います。
https://www.w3.org/TR/wai-aria-practices/examples/carousel/carousel-1.html

**Comment by momdo** [comment]
examplesの差分を取ると、（最新の1.2と比較して）結構差分が出てますね
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FNOTE-wai-aria-practices-1.1-20190207%2Fexamples%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2Fwai-aria-practices-1.2%2Fexamples%2F

Link Checkerだと、下記スクリーンショットのとおりでそこそこ壊れてます。
https://validator.w3.org/checklink?uri=https%3A%2F%2Fwaic.jp%2Fdocs%2F2019%2FNOTE-wai-aria-practices-1.1-20190207%2F%23carousel&hide_type=all&recursive=on&depth=1&check=Check

![image](https://user-images.githubusercontent.com/8347177/150307099-99b475eb-f588-4b36-bf43-0fe319158a70.png)

**Comment by bakera** [comment]
/wai-aria-practices/ → /wai-aria-practices-1.1/ とすると繋がる模様
本家ではしれっと修正されている。
余裕があれば直す方向で。

**Comment by bakera** [comment]
いや、これ本家だと相対URL指定だから壊れてないんですね。

```
<li><a href="examples/dialog-modal/dialog.html">Modal Dialog Example</a>: Demonstrates multiple layers of modal dialogs with both small and large amounts of content.</li>
```

**Comment by bakera** [comment]
全体的に /wai-aria-practices/ → /wai-aria-practices-1.1/ を実施すれば良さそう。
